# Gatus Config
# storage:
#   type: sqlite
#   path: /data/data.db
# Cant seem to get this working
# security:
#   basic:
#     username: "admin"
#     password-bcrypt-base64: "YidiL1JhSmVMYTRiTG1YcmliYngvQU1tMlBON1NTYXcwWVFnWnpHJw=="
#     # gothetooKiew2qu
web:
    port: 80
ui:
    title: Health Dashboard
    description: Gatus monitoring dashboard
    header: Health Status
    buttons:
        - name: Blog
          link: https://garymcdermott.net/
        - name: GitHub
          link: https://github.com/mcdermg
        - name: LinkedIn
          link: https://www.linkedin.com/in/garymcdermott
alerting:
    slack:
        webhook-url: ENC[AES256_GCM,data:biMgaQuPDhi7WMgocO2YyLHZpp9jYN13FJ1wum5EUHaHk4PrqFsD+oa45qFSJHvVO3HdTbiSaPs6Po031hecU8Of5HgEfK1kNAJ4URND0g==,iv:eCv224S5qk1P1OXibjWRiyZwBU3SOwQd87+AdYaRtug=,tag:YenFB6n9fVn9kXcMFDvE5A==,type:str]
        default-alert:
            description: Healthcheck failed 3 times in a row
            send-on-resolved: true
            failure-threshold: 3
            success-threshold: 3
default-endpoint:
    group: Websites
    interval: 15m
    alerts:
        - type: slack
    conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 1000'
        # 5 min minimum
        - '[DOMAIN_EXPIRATION] > 720h'
        - '[CERTIFICATE_EXPIRATION] > 240h'
internal-endpoint:
    group: Cluster
    interval: 5m
    alerts:
        - type: slack
    conditions:
        - '[CONNECTED] == true'
        - '[RESPONSE_TIME] < 200'
endpoints:
    - name: garymcdermott
      !!merge <<:
        group: Websites
        interval: 15m
        alerts:
            - type: slack
        conditions:
            - '[STATUS] == 200'
            - '[RESPONSE_TIME] < 1000'
            # 5 min minimum
            - '[DOMAIN_EXPIRATION] > 720h'
            - '[CERTIFICATE_EXPIRATION] > 240h'
      url: https://garymcdermott.net/
    #- name: celestialindustries
    #  <<: *defaults
    #  url: "https://celestialindustries.info/"
    #  conditions:
    #    - "[RESPONSE_TIME] < 1500"
    #    - "[STATUS] == 200"
    #    - "[DOMAIN_EXPIRATION] > 720h" # 5min minium
    #    - "[CERTIFICATE_EXPIRATION] > 240h"
    - name: Telecentro
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      group: Network
      url: icmp://192.168.0.1
    # - name: Telecentro-login
    #   <<: *internal
    #   group: Network
    #   url: "icmp://192.168.0.1"
    #- name: Mikrotik
    #  <<: *internal
    #  group: Network
    #  url: "icmp://192.168.0.98"
    - name: control
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.66
    - name: node-1
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.65
    - name: node-2
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.64
    - name: node-3
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.63
      #- name: zero-1
      #  <<: *internal
      #  url: "icmp://192.168.1.61"
      #  group: Monitoring
      #- name: zero-2
      #  <<: *internal
      #  url: "icmp://192.168.1.62"
      #  group: Monitoring
      #- name: zero-1 Prometheus
      #  <<: *internal
      #  url: "http://192.168.1.83:9090/-/healthy"
      #  group: Monitoring
      #  conditions:
      #    - "[CONNECTED] == true"
      #    - "[RESPONSE_TIME] < 200"
      #    - "[BODY] == Prometheus is Healthy."
      ## TODO turning off for multi arch build setup
      # - name: Prometheus-service
      #   <<: *internal
      #   group: Services
      #   url: "http://192.168.0.241/-/healthy"
      #   conditions:
      #     - "[STATUS] == 200"
      #     - "[RESPONSE_TIME] < 1000"
      #     - "[BODY] == Prometheus is Healthy."
      # - name: Grafana-service
      #   <<: *internal
      #   group: Services
      #   url: "http://192.168.0.242/api/health"
      #   conditions:
      #     - "[STATUS] == 200"
      #     - "[RESPONSE_TIME] < 1000"
      #     - "[BODY].database == ok"
# Needs ssh password auth to be on, not ideal
# etc/ssh/sshd_config to contain PasswordAuthentication yes
# has to use v.5.6.0 at minium
# - name: ssh-example
#   url: "ssh://192.168.0.66:22" # port is optional. Default is 22.
#   group: ssh
#   ssh:
#     username: "pi"
#     password: "chefVancouver866"
#   body: |
#     {
#       "command": "uptime"
#     }
#   interval: 1m
#   conditions:
#     - "[CONNECTED] == true"
#     - "[STATUS] == 0"
#
# - name: ssh-example-2
#   url: "ssh://192.168.0.65:22" # port is optional. Default is 22.
#   group: ssh
#   ssh:
#     username: "pi"
#     password: "chefVancouver866"
#   body: |
#     {
#       "command": "uptime"
#     }
#   interval: 1m
#   conditions:
#     - "[CONNECTED] == true"
#     - "[STATUS] == 0"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148cexwa3lg8m7qxh6tdw90q2ntpngx2v8kvjw2xcdkp6kpq7n5nsxls8k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYTlBdUlKTVhIQzhBRzdG
            VlIwY0huZEFXNjZOR2UwTlFxakNaWEZkL2hJCjBJTlc1S0tiYTVZcUxaa3IrTG5p
            a3BncG1OM2tneXFPaTBFdUZyb2ZFWWMKLS0tIDlxalNjcDN1RXFjVzBveGtRSXRN
            b1ZwQXdWb0FtQ3E4R0xWQ1h4YmpBVXMKVdhqvBBDzZ26+YFZFZOqlZWHijfT9xwL
            T1zfLGhiPhb57y8Kf4RfaHngWCkbtx+hLsWho2YtLk7w8qv3p1HsUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T21:57:03Z"
    mac: ENC[AES256_GCM,data:sq0pAsEJ4eL/QNeEuH5XeLwf+MRvIUSV9p5NVKPHfUgpt/+5yoxdPttZqaPbg/JQKKQld9IqRsl9989AngvxM7qDsXDY+v/pQK9t/6zvBqyh5lgPqnG9kEEtJ3CUnEjflxrZMvEGGFzsdshkTtYdBhmvkB48cVyJ2Yd0djMttBA=,iv:lJHjOnN/n8z3yDjXc6NhV40MSLJrfBKOf+q7X55m5Tk=,tag:nGMoKjhWBGUYgEL0hECZSA==,type:str]
    pgp: []
    encrypted_regex: ^(webhook-url)$
    version: 3.7.2
