# Gatus Config

# storage:
#   type: sqlite
#   path: /data/data.db

# Cant seem to get this working
# security:
#   basic:
#     username: "admin"
#     password-bcrypt-base64: "YidiL1JhSmVMYTRiTG1YcmliYngvQU1tMlBON1NTYXcwWVFnWnpHJw=="
#     # gothetooKiew2qu

web:
  port: 80

ui:
  title: Health Dashboard
  description: Gatus monitoring dashboard
  header: Health Status
  buttons:
    - name: Blog
      link: 'https://garymcdermott.net/'
    - name: GitHub
      link: 'https://github.com/mcdermg'
    - name: LinkedIn
      link: 'https://www.linkedin.com/in/garymcdermott'

alerting:
  slack:
    webhook-url: "https://hooks.slack.com/services/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"
    default-alert:
      description: "Healthcheck failed 3 times in a row"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 3

default-endpoint: &defaults
  group: Websites
  interval: 15m
  alerts:
    - type: slack
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 1000"
    - "[DOMAIN_EXPIRATION] > 720h" # 5 min minimum
    - "[CERTIFICATE_EXPIRATION] > 240h"

internal-endpoint: &internal
  group: Cluster
  interval: 5m
  alerts:
    - type: slack
  conditions:
      - "[CONNECTED] == true"
      - "[RESPONSE_TIME] < 200"

endpoints:
  - name: garymcdermott
    <<: *defaults
    url: "https://garymcdermott.net/"

  #- name: celestialindustries
  #  <<: *defaults
  #  url: "https://celestialindustries.info/"
  #  conditions:
  #    - "[RESPONSE_TIME] < 1500"
  #    - "[STATUS] == 200"
  #    - "[DOMAIN_EXPIRATION] > 720h" # 5min minium
  #    - "[CERTIFICATE_EXPIRATION] > 240h"

  - name: Telecentro
    <<: *internal
    group: Network
    url: "icmp://192.168.0.1"

  # - name: Telecentro-login
  #   <<: *internal
  #   group: Network
  #   url: "icmp://192.168.0.1"

  #- name: Mikrotik
  #  <<: *internal
  #  group: Network
  #  url: "icmp://192.168.0.98"

  - name: control
    <<: *internal
    url: "icmp://192.168.0.66"

  - name: node-1
    <<: *internal
    url: "icmp://192.168.0.65"

  - name: node-2
    <<: *internal
    url: "icmp://192.168.0.64"

  - name: node-3
    <<: *internal
    url: "icmp://192.168.0.63"

  #- name: zero-1
  #  <<: *internal
  #  url: "icmp://192.168.1.61"
  #  group: Monitoring

  #- name: zero-2
  #  <<: *internal
  #  url: "icmp://192.168.1.62"
  #  group: Monitoring

  #- name: zero-1 Prometheus
  #  <<: *internal
  #  url: "http://192.168.1.83:9090/-/healthy"
  #  group: Monitoring
  #  conditions:
  #    - "[CONNECTED] == true"
  #    - "[RESPONSE_TIME] < 200"
  #    - "[BODY] == Prometheus is Healthy."

  ## TODO turning off for multi arch build setup
  # - name: Prometheus-service
  #   <<: *internal
  #   group: Services
  #   url: "http://192.168.0.241/-/healthy"
  #   conditions:
  #     - "[STATUS] == 200"
  #     - "[RESPONSE_TIME] < 1000"
  #     - "[BODY] == Prometheus is Healthy."

  # - name: Grafana-service
  #   <<: *internal
  #   group: Services
  #   url: "http://192.168.0.242/api/health"
  #   conditions:
  #     - "[STATUS] == 200"
  #     - "[RESPONSE_TIME] < 1000"
  #     - "[BODY].database == ok"

# Needs ssh password auth to be on, not ideal
# etc/ssh/sshd_config to contain PasswordAuthentication yes
# has to use v.5.6.0 at minium
  # - name: ssh-example
  #   url: "ssh://192.168.0.66:22" # port is optional. Default is 22.
  #   group: ssh
  #   ssh:
  #     username: "pi"
  #     password: "chefVancouver866"
  #   body: |
  #     {
  #       "command": "uptime"
  #     }
  #   interval: 1m
  #   conditions:
  #     - "[CONNECTED] == true"
  #     - "[STATUS] == 0"
  #
  # - name: ssh-example-2
  #   url: "ssh://192.168.0.65:22" # port is optional. Default is 22.
  #   group: ssh
  #   ssh:
  #     username: "pi"
  #     password: "chefVancouver866"
  #   body: |
  #     {
  #       "command": "uptime"
  #     }
  #   interval: 1m
  #   conditions:
  #     - "[CONNECTED] == true"
  #     - "[STATUS] == 0"
