storage:
    type: sqlite
    path: ./data/data.db
web:
    port: 80
ui:
    title: Health Dashboard
    description: Gatus monitoring dashboard
    header: Health Status
    buttons:
        - name: Blog
          link: https://garymcdermott.net/
        - name: GitHub
          link: https://github.com/mcdermg
        - name: LinkedIn
          link: https://www.linkedin.com/in/garymcdermott
alerting:
    slack:
        webhook-url: ENC[AES256_GCM,data:gz+WfAxGgRkSY8uMDVlF6sEpXZVeVx7ooY6DbmGBSOFp2HEE39aZKwpeBHGIUMSo969t7v7EEaA5wCLFYlzoaZB5hOA5xDhz+mFyUAoDVA==,iv:ALTSpY71Kw/M+dLYf7TTigg4561ENpubmrXiFvKfXIs=,tag:EOQylH2N3IetmJ6vuPc39A==,type:str]
        default-alert:
            description: Healthcheck failed 3 times in a row
            send-on-resolved: true
            failure-threshold: 3
            success-threshold: 3
default-endpoint:
    group: Websites
    interval: 15m
    alerts:
        - type: slack
    conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 1000'
        # 5 min minimum
        - '[DOMAIN_EXPIRATION] > 720h'
        - '[CERTIFICATE_EXPIRATION] > 240h'
internal-endpoint:
    group: Cluster
    interval: 5m
    alerts:
        - type: slack
    conditions:
        - '[CONNECTED] == true'
        - '[RESPONSE_TIME] < 200'
endpoints:
    - name: garymcdermott
      !!merge <<:
        group: Websites
        interval: 15m
        alerts:
            - type: slack
        conditions:
            - '[STATUS] == 200'
            - '[RESPONSE_TIME] < 1000'
            # 5 min minimum
            - '[DOMAIN_EXPIRATION] > 720h'
            - '[CERTIFICATE_EXPIRATION] > 240h'
      conditions:
        - '[RESPONSE_TIME] < 4000'
      url: https://www.garymcdermott.net
    - name: Telecentro
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      group: Network
      url: icmp://192.168.0.1
    - name: control
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.66
    - name: node-1
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.65
    - name: node-2
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.64
    - name: node-3
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      url: icmp://192.168.0.63
    - name: Deployment-test-service
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      group: Services
      url: http://192.168.0.241
      conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 1000'
    - name: Grafana-service
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      group: Services
      url: http://192.168.0.242/api/health
      conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 1000'
        - '[BODY].database == ok'
    - name: Prometheus-service
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      group: Services
      url: http://192.168.0.243/-/healthy
      conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 1000'
        - '[BODY] == Prometheus is Healthy.'
    - name: Longhiorn-service
      !!merge <<:
        group: Cluster
        interval: 5m
        alerts:
            - type: slack
        conditions:
            - '[CONNECTED] == true'
            - '[RESPONSE_TIME] < 200'
      group: Services
      url: http://192.168.0.244
      conditions:
        - '[STATUS] == 200'
        - '[RESPONSE_TIME] < 1000'
#    - name: mosquitto
#      url: "tcp://192.168.0.35:1883"
#      group: Sensors
#      interval: 60s
#      conditions: 
#        - "[CONNECTED] == true"
#    - name: sensor-01
#      <<: *internal
#      group: Sensors
#      url: icmp://192.168.0.81
#      interval: 60s
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age148cexwa3lg8m7qxh6tdw90q2ntpngx2v8kvjw2xcdkp6kpq7n5nsxls8k8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TDIxeXk0bXZvS1pZVnBq
            Y0c5ZmhqUDhJZHBjaDB5dGtDSlNRUDZXbjBJClNmUkFOL09HNnFPM292bWxkb3Bl
            WS9WaGNoZGJSNmt0RE12b056V2Vyd3cKLS0tIE1raFhyM1dsOEZpeTNSTE5zMFlP
            VndsM2djbUpvUnlHQzE5U1d4QWtDTGcK6CqzKJs7VDagdj7355+I9YgrcMzimuSo
            hBiUmTVoZT3Jsm2a/3j+JhyG7bEmghjLS7g7GXEeaKwl/I1sy06Sig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T17:05:33Z"
    mac: ENC[AES256_GCM,data:M9BryN/P5ehJGRKuQqZLUTJGoLrqElMNca8AJsrirZ3yeQGsxWp64LD1nwXc8EtxdEvrFBH+EUECHSWdwH6mFwLF+1kPoD456zgrDVS+OjB1LzvyIfSkEAXOMCTLJ3Oe4QhjXp3TBsJxBvwqslv9id6/hAvMx3/qK0/6pshMEU0=,iv:i5ct+jptSbQZeeAnekNOSuJG+XmCUZAYVkRwWXhxFhE=,tag:rO/TXTMm+Dbc3gD6KC4ImQ==,type:str]
    pgp: []
    encrypted_regex: ^(webhook-url)$
    version: 3.7.2
