name: build and push image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     platform:
    #       - linux/amd64
    #       - linux/arm/v6
    #       - linux/arm/v7
    #       - linux/arm64    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get SOPS latest semantic version
        id: get-sops-version
        run: |
          SOPS_VERSION=$(curl -s https://api.github.com/repos/getsops/sops/releases/latest | grep -oP '"tag_name": "\K[^"]+')
          echo $SOPS_VERSION
          echo "SOPS_VERSION=$SOPS_VERSION" >> $GITHUB_ENV

      - name: Sops Binary Installer
        uses: mdgreenwald/mozilla-sops-action@v1
        with:
          version: '${{ steps.get-sops-version.outputs.SOPS_VERSION }}'
        #id: install

      - name: Get SOPS latest semantic version
        run: |
          sops --version
          sops --decrypt ./config.enc.yaml > config.yaml 

      - name: Debug-1
        run: |
          cat config.yaml
          echo ''
          cat config.enc.yaml

      - name: Set up QEMU
        id: Set_up_QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        id: Set_up_Docker_Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to DockerHub
        id: Login_to_DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_publish
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          platforms: linux/amd64,linux/arm,linux/arm64
          #platforms: ${{ matrix.platform }}
          push: true
          tags: mcdermg/gatus:latest

      - uses: act10ns/slack@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
