name: build and push image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AGE key for decryption for SOPS
        id: setup-age-key
        run: |
          echo "${{ secrets.AGE_KEY }}" >  keys.txt
          echo "SOPS_AGE_KEY_FILE=$(pwd)/keys.txt" >> $GITHUB_ENV

      - name: Get SOPS latest semantic version
        id: get-sops-version
        run: |
          SOPS_VERSION=$(curl -s https://api.github.com/repos/getsops/sops/releases/latest | grep -oP '"tag_name": "\K[^"]+' | sed 's/^v//')
          echo "SOPS_VERSION=$SOPS_VERSION" >> $GITHUB_ENV
          echo $SOPS_VERSION

      - name: Install SOPS from deb package
        id: install-sops
        run: |
          echo $SOPS_VERSION
          URL="https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops_${SOPS_VERSION}_amd64.deb"
          wget $URL -O sops.deb
          sudo dpkg -i sops.deb

      - name: SOPS decrypt yaml config
        id: sops-decrypt-config-yaml
        run: |
          sops --decrypt --age $(cat $SOPS_AGE_KEY_FILE | grep -oP "public key: \K(.*)") ./config.enc.yaml > config.yaml 

      - name: Set up QEMU
        id: Set_up_QEMU
        uses: docker/setup-qemu-action@v3.1.0

      - name: Set up Docker Buildx
        id: Set_up_Docker_Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Login to DockerHub
        id: Login_to_DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build_and_publish
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: mcdermg/gatus:latest

      - uses: act10ns/slack@v2.1.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
